use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'RJUtils_Swift_Example' do
  pod 'RJUtils_Swift', :path => '../'

  target 'RJUtils_Swift_Tests' do
    inherit! :search_paths

    
  end
end
